using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.Data.Sqlite;using Microsoft.EntityFrameworkCore;using POS.Server.Controllers;using POS.Server.Data;using POS.Server.Services;using POS.Shared.DTOs;using POS.Shared.Entities;using Xunit;
namespace POS.Tests;
public class Sprint4Tests
{
 [Fact]public async Task ValidDispatch_IsCreated(){await using var f=await F.Create();var x=await f.Dispatch.CreateAsync(Request(),1);Assert.Equal(DispatchStatuses.Confirmed,x.Status);Assert.Single(x.Details);}
 [Fact]public async Task Dispatch_ReducesStock(){await using var f=await F.Create();await f.Dispatch.CreateAsync(Request(),1);f.Db.ChangeTracker.Clear();Assert.Equal(90,(await f.Db.InventoryProducts.SingleAsync()).CurrentStock);}
 [Fact]public async Task Dispatch_CreatesExitMovement(){await using var f=await F.Create();var d=await f.Dispatch.CreateAsync(Request(),1);var m=await f.Db.InventoryMovements.SingleAsync();Assert.Equal(InventoryMovementTypes.DispatchExit,m.MovementType);Assert.Equal($"DESPACHO:{d.Id}",m.Reference);}
 [Fact]public async Task NonPositiveDispatch_IsRejected(){await using var f=await F.Create();var r=Request();r.Details[0].Quantity=0;await Assert.ThrowsAsync<BusinessValidationException>(()=>f.Dispatch.CreateAsync(r,1));}
 [Fact]public async Task InactiveDispatchProduct_IsRejected(){await using var f=await F.Create();f.Product.IsActive=false;await f.Db.SaveChangesAsync();await Assert.ThrowsAsync<BusinessValidationException>(()=>f.Dispatch.CreateAsync(Request(),1));}
 [Fact]public async Task DispatchAboveStock_IsRejected(){await using var f=await F.Create();var r=Request();r.Details[0].Quantity=101;await Assert.ThrowsAsync<BusinessValidationException>(()=>f.Dispatch.CreateAsync(r,1));}
 [Fact]public async Task DispatchFailure_RollsBackAll(){await using var f=await F.Create(true);f.Failing!.FailSecond();await Assert.ThrowsAsync<InvalidOperationException>(()=>f.Dispatch.CreateAsync(Request(),1));f.Db.ChangeTracker.Clear();Assert.Empty(await f.Db.Dispatches.ToListAsync());Assert.Empty(await f.Db.DispatchDetails.ToListAsync());Assert.Empty(await f.Db.InventoryMovements.ToListAsync());Assert.Equal(100,(await f.Db.InventoryProducts.SingleAsync()).CurrentStock);}
 [Fact]public async Task ConfirmTwice_DoesNotDiscountAgain(){await using var f=await F.Create();var d=await f.Dispatch.CreateAsync(Request(),1);await f.Dispatch.ConfirmAsync(d.Id,1);await f.Dispatch.ConfirmAsync(d.Id,1);f.Db.ChangeTracker.Clear();Assert.Equal(90,(await f.Db.InventoryProducts.SingleAsync()).CurrentStock);}
 [Fact]public async Task ConfirmTwice_DoesNotDuplicateMovement(){await using var f=await F.Create();var d=await f.Dispatch.CreateAsync(Request(),1);await f.Dispatch.ConfirmAsync(d.Id,1);Assert.Single(await f.Db.InventoryMovements.ToListAsync());}
 [Fact]public async Task FinishLot_CreatesProductionEntry(){await using var f=await F.Create();var lot=await f.InProgressLot();await f.Production.FinishAsync(lot.Id,new(){ProducedQuantity=5},1);Assert.Equal(InventoryMovementTypes.ProductionEntry,(await f.Db.InventoryMovements.SingleAsync()).MovementType);}
 [Fact]public async Task RepeatedFinish_DoesNotDuplicateMovement(){await using var f=await F.Create();var lot=await f.InProgressLot();await f.Production.FinishAsync(lot.Id,new(){ProducedQuantity=5},1);await f.Production.FinishAsync(lot.Id,new(){ProducedQuantity=5},1);Assert.Single(await f.Db.InventoryMovements.ToListAsync());}
 [Fact]public async Task MovementHistory_ReturnsRows(){await using var f=await F.Create();await f.Dispatch.CreateAsync(Request(),1);Assert.Single(await new InventoryMovementsController(f.Db).Get(null,null,null,null,null));}
 [Fact]public async Task MovementHistory_FiltersProduct(){await using var f=await F.Create();await f.Dispatch.CreateAsync(Request(),1);Assert.Single(await new InventoryMovementsController(f.Db).Get(1,null,null,null,null));Assert.Empty(await new InventoryMovementsController(f.Db).Get(99,null,null,null,null));}
 [Fact]public async Task MovementHistory_FiltersType(){await using var f=await F.Create();await f.Dispatch.CreateAsync(Request(),1);Assert.Single(await new InventoryMovementsController(f.Db).Get(null,InventoryMovementTypes.DispatchExit,null,null,null));Assert.Empty(await new InventoryMovementsController(f.Db).Get(null,InventoryMovementTypes.ProductionEntry,null,null,null));}
 [Fact]public async Task MovementHistory_FiltersDateRange(){await using var f=await F.Create();await f.Dispatch.CreateAsync(Request(),1);Assert.Single(await new InventoryMovementsController(f.Db).Get(null,null,DateTime.Today,DateTime.Today,null));Assert.Empty(await new InventoryMovementsController(f.Db).Get(null,null,DateTime.Today.AddDays(1),null,null));}
 [Fact]public async Task Traceability_ReturnsLot(){await using var f=await F.Create();var lot=await f.InProgressLot();var r=await new TraceabilityController(f.Db).Get(lot.Code);Assert.IsType<OkObjectResult>(r.Result);}
 [Fact]public async Task Traceability_IncludesMaterials(){await using var f=await F.Create();var lot=await f.InProgressLot(true);var ok=Assert.IsType<OkObjectResult>((await new TraceabilityController(f.Db).Get(lot.Code)).Result);Assert.Single(Assert.IsType<LotTraceabilityResponse>(ok.Value).Lot.Materials);}
 [Fact]public async Task Traceability_IncludesProduct(){await using var f=await F.Create();var lot=await f.InProgressLot();var ok=Assert.IsType<OkObjectResult>((await new TraceabilityController(f.Db).Get(lot.Code)).Result);Assert.Equal("Palmito",Assert.IsType<LotTraceabilityResponse>(ok.Value).Lot.ProductName);}
 [Fact]public void Management_CannotRegisterDispatch(){var roles=PostRoles();Assert.DoesNotContain("Gerencia",roles);}
 [Fact]public void Warehouse_CanRegisterDispatch(){Assert.Contains("Almacén",PostRoles());}
 [Fact]public async Task ProductionReport_ReturnsRows(){await using var f=await F.Create();await f.InProgressLot();Assert.Single(await new ReportsController(f.Db).Production(null,null));}
 [Fact]public async Task InventoryReport_ReturnsRows(){await using var f=await F.Create();var rows=await new ReportsController(f.Db).Inventory();Assert.Equal(2,rows.Count);}
 [Fact]public async Task DispatchReport_ReturnsRows(){await using var f=await F.Create();await f.Dispatch.CreateAsync(Request(),1);Assert.Single(await new ReportsController(f.Db).Dispatches(null,null));}
 static string PostRoles()=>typeof(DispatchesController).GetMethod(nameof(DispatchesController.Post))!.GetCustomAttributes(typeof(AuthorizeAttribute),true).Cast<AuthorizeAttribute>().Single().Roles!;
 static CreateDispatchRequest Request()=>new(){Date=DateTime.Today,Destination="Santa Cruz",Details=[new(){ProductId=1,Quantity=10}]};
 sealed class F:IAsyncDisposable
 {
  public required SqliteConnection Connection{get;init;}public required AppDbContext Db{get;init;}public required DispatchService Dispatch{get;init;}public required ProductionLotService Production{get;init;}public required InventoryProduct Product{get;init;}public FailingDb?Failing=>Db as FailingDb;
  public static async Task<F>Create(bool failing=false){var c=new SqliteConnection("Data Source=:memory:");await c.OpenAsync();var o=new DbContextOptionsBuilder<AppDbContext>().UseSqlite(c).Options;AppDbContext db=failing?new FailingDb(o):new AppDbContext(o);await db.Database.EnsureCreatedAsync();var role=new RoleEntity{Id=1,Name="Almacén",IsActive=true};var u=new User{Id=1,Name="A",LastName="B",Email="a@b.bo",Username="almacen",PasswordHash="x",Role=role,RoleId=1,IsActive=true};var p=new InventoryProduct{Id=1,Name="Palmito",UnitOfMeasure="unidad",CurrentStock=100,MinimumStock=10,IsActive=true};var m=new RawMaterial{Id=1,Name="Palmito fresco",UnitOfMeasure="kg",CurrentStock=100,MinimumStock=10,IsActive=true};db.AddRange(role,u,p,m);await db.SaveChangesAsync();return new(){Connection=c,Db=db,Dispatch=new(db),Production=new(db),Product=p};}
  public async Task<ProductionLot>InProgressLot(bool detail=false){var l=new ProductionLot{ProductId=1,UserId=1,Code="LP-S4",StartDate=DateTime.Today,PlannedQuantity=10,ProducedQuantity=0,Status=ProductionLotStatuses.InProgress};if(detail)l.Details.Add(new(){RawMaterialId=1,QuantityUsed=2});Db.ProductionLots.Add(l);await Db.SaveChangesAsync();return l;}
  public async ValueTask DisposeAsync(){await Db.DisposeAsync();await Connection.DisposeAsync();}
 }
 sealed class FailingDb(DbContextOptions<AppDbContext>o):AppDbContext(o){int saves;bool fail;public void FailSecond(){saves=0;fail=true;}public override Task<int>SaveChangesAsync(CancellationToken t=default){if(fail&&++saves==2)throw new InvalidOperationException("simulado");return base.SaveChangesAsync(t);}}
}
